org: [[SLS_ORG_NAME]]
app: [[SLS_APP_NAME]]
service: [[SLS_SERVICE_NAME]]

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: sls-cognito-user-managment-${self:provider.stage}
    serverSideEncryption: AES256
  environment:
    POOL_ID: [[COGNITO_POOL_ID]]
    CLIENT_ID: [[COGNITO_CLIENT_ID]]
    
functions:
  signup:
    handler: handler.signup 
    events:
      - http:
          path: /user/signup
          method: post
          cors: true
  confirmRegistration:
    handler: handler.confirmRegistration 
    events:
      - http:
          path: /user/confirmRegistration
          method: post
          cors: true
  resendConfirmationCode:
    handler: handler.resendConfirmationCode 
    events:
      - http:
          path: /user/resendConfirmationCode
          method: post
          cors: true             

plugins:
  - serverless-deployment-bucket    
  - serverless-offline